package com.springTest.getMeterData;

import com.dventus.TestBenchResults;

//Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
* CalibrationTest generated by hbm2java
*/

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class CalibrationTest implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy
                    = GenerationType.AUTO)
	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private String calibrationState;
	private Integer cr;
	private Integer elo;
	private Integer ehi;
	private Integer gco;
	private Integer poff;
	private Integer phCo;
	private Integer stCint;
	private Integer stCfra;
	private Integer vr;
	private Integer phCo0;
	private Integer phCo1;
	private Integer phCo2;
	private Integer phCo3;
	private String meterIdnumeric;
	private String errors;
	private String idpasswordStatus;

	public CalibrationTest() {
	}

	public CalibrationTest(TestBase testBase) {
		this.testBase = testBase;
	}

	public CalibrationTest(TestBenchResults testBenchResults, TestBase testBase, String calibrationState, Integer cr,
			Integer elo, Integer ehi, Integer gco, Integer poff, Integer phCo, Integer stCint, Integer stCfra,
			Integer vr, Integer phCo0, Integer phCo1, Integer phCo2, Integer phCo3, String meterIdnumeric,
			String errors, String idpasswordStatus) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.calibrationState = calibrationState;
		this.cr = cr;
		this.elo = elo;
		this.ehi = ehi;
		this.gco = gco;
		this.poff = poff;
		this.phCo = phCo;
		this.stCint = stCint;
		this.stCfra = stCfra;
		this.vr = vr;
		this.phCo0 = phCo0;
		this.phCo1 = phCo1;
		this.phCo2 = phCo2;
		this.phCo3 = phCo3;
		this.meterIdnumeric = meterIdnumeric;
		this.errors = errors;
		this.idpasswordStatus = idpasswordStatus;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public String getCalibrationState() {
		return this.calibrationState;
	}

	public void setCalibrationState(String calibrationState) {
		this.calibrationState = calibrationState;
	}

	public Integer getCr() {
		return this.cr;
	}

	public void setCr(Integer cr) {
		this.cr = cr;
	}

	public Integer getElo() {
		return this.elo;
	}

	public void setElo(Integer elo) {
		this.elo = elo;
	}

	public Integer getEhi() {
		return this.ehi;
	}

	public void setEhi(Integer ehi) {
		this.ehi = ehi;
	}

	public Integer getGco() {
		return this.gco;
	}

	public void setGco(Integer gco) {
		this.gco = gco;
	}

	public Integer getPoff() {
		return this.poff;
	}

	public void setPoff(Integer poff) {
		this.poff = poff;
	}

	public Integer getPhCo() {
		return this.phCo;
	}

	public void setPhCo(Integer phCo) {
		this.phCo = phCo;
	}

	public Integer getStCint() {
		return this.stCint;
	}

	public void setStCint(Integer stCint) {
		this.stCint = stCint;
	}

	public Integer getStCfra() {
		return this.stCfra;
	}

	public void setStCfra(Integer stCfra) {
		this.stCfra = stCfra;
	}

	public Integer getVr() {
		return this.vr;
	}

	public void setVr(Integer vr) {
		this.vr = vr;
	}

	public Integer getPhCo0() {
		return this.phCo0;
	}

	public void setPhCo0(Integer phCo0) {
		this.phCo0 = phCo0;
	}

	public Integer getPhCo1() {
		return this.phCo1;
	}

	public void setPhCo1(Integer phCo1) {
		this.phCo1 = phCo1;
	}

	public Integer getPhCo2() {
		return this.phCo2;
	}

	public void setPhCo2(Integer phCo2) {
		this.phCo2 = phCo2;
	}

	public Integer getPhCo3() {
		return this.phCo3;
	}

	public void setPhCo3(Integer phCo3) {
		this.phCo3 = phCo3;
	}

	public String getMeterIdnumeric() {
		return this.meterIdnumeric;
	}

	public void setMeterIdnumeric(String meterIdnumeric) {
		this.meterIdnumeric = meterIdnumeric;
	}

	public String getErrors() {
		return this.errors;
	}

	public void setErrors(String errors) {
		this.errors = errors;
	}

	public String getIdpasswordStatus() {
		return this.idpasswordStatus;
	}

	public void setIdpasswordStatus(String idpasswordStatus) {
		this.idpasswordStatus = idpasswordStatus;
	}

}
