package com.springTest.getMeterData;

import com.dventus.TestBenchResults;

//Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
* EnergyRegisterTest generated by hbm2java
*/

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class EnergyRegisterTest implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy
                    = GenerationType.AUTO)
	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private Float endEnergy;
	private Float dosageEnergy;
	private Float percentError;
	private Float startEnergy;
	private String evaluation;

	public EnergyRegisterTest() {
	}

	public EnergyRegisterTest(TestBase testBase) {
		this.testBase = testBase;
	}

	public EnergyRegisterTest(TestBenchResults testBenchResults, TestBase testBase, Float endEnergy, Float dosageEnergy,
			Float percentError, Float startEnergy, String evaluation) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.endEnergy = endEnergy;
		this.dosageEnergy = dosageEnergy;
		this.percentError = percentError;
		this.startEnergy = startEnergy;
		this.evaluation = evaluation;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public String getEvaluation() {
		return evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}
	
	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public Float getEndEnergy() {
		return this.endEnergy;
	}

	public void setEndEnergy(Float endEnergy) {
		this.endEnergy = endEnergy;
	}

	public Float getDosageEnergy() {
		return this.dosageEnergy;
	}

	public void setDosageEnergy(Float dosageEnergy) {
		this.dosageEnergy = dosageEnergy;
	}

	public Float getPercentError() {
		return this.percentError;
	}

	public void setPercentError(Float percentError) {
		this.percentError = percentError;
	}

	public Float getStartEnergy() {
		return this.startEnergy;
	}

	public void setStartEnergy(Float startEnergy) {
		this.startEnergy = startEnergy;
	}

}
