package com.springTest.getMeterData;

import com.dventus.Persistence;
import com.dventus.TestBenchResults;

//Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
* StartingCurrentTest generated by hbm2java
*/
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class StartingCurrentTest extends Persistence implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy
                    = GenerationType.AUTO)
	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private Integer edgesCountStartingI;
	private String alirTyp;
	private String evaluation;

	public StartingCurrentTest() {
	}

	public StartingCurrentTest(TestBase testBase) {
		this.testBase = testBase;
	}

	public StartingCurrentTest(TestBenchResults testBenchResults, TestBase testBase, Integer edgesCountStartingI,
			String alirTyp, String evaluation) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.edgesCountStartingI = edgesCountStartingI;
		this.alirTyp = alirTyp;
		this.evaluation = evaluation;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public Integer getEdgesCountStartingI() {
		return this.edgesCountStartingI;
	}

	public void setEdgesCountStartingI(Integer edgesCountStartingI) {
		this.edgesCountStartingI = edgesCountStartingI;
	}

	public String getAlirTyp() {
		return this.alirTyp;
	}

	public void setAlirTyp(String alirTyp) {
		this.alirTyp = alirTyp;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

}
