package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * BoardTest generated by hbm2java
 */
public class BoardTest implements java.io.Serializable {

	private Long hjid;
	private CircuitBoard circuitBoard;
	private String backCoverSn;
	private String batVoltage;
	private String testDate;
	private String testFileName;
	private String testPersonnel;
	private String testResult;
	private String testTime;

	public BoardTest() {
	}

	public BoardTest(CircuitBoard circuitBoard, String backCoverSn, String batVoltage, String testDate,
			String testFileName, String testPersonnel, String testResult, String testTime) {
		this.circuitBoard = circuitBoard;
		this.backCoverSn = backCoverSn;
		this.batVoltage = batVoltage;
		this.testDate = testDate;
		this.testFileName = testFileName;
		this.testPersonnel = testPersonnel;
		this.testResult = testResult;
		this.testTime = testTime;
	}

	public Long getHjid() {
		return this.hjid;
	}

	public void setHjid(Long hjid) {
		this.hjid = hjid;
	}

	public CircuitBoard getCircuitBoard() {
		return this.circuitBoard;
	}

	public void setCircuitBoard(CircuitBoard circuitBoard) {
		this.circuitBoard = circuitBoard;
	}

	public String getBackCoverSn() {
		return this.backCoverSn;
	}

	public void setBackCoverSn(String backCoverSn) {
		this.backCoverSn = backCoverSn;
	}

	public String getBatVoltage() {
		return this.batVoltage;
	}

	public void setBatVoltage(String batVoltage) {
		this.batVoltage = batVoltage;
	}

	public String getTestDate() {
		return this.testDate;
	}

	public void setTestDate(String testDate) {
		this.testDate = testDate;
	}

	public String getTestFileName() {
		return this.testFileName;
	}

	public void setTestFileName(String testFileName) {
		this.testFileName = testFileName;
	}

	public String getTestPersonnel() {
		return this.testPersonnel;
	}

	public void setTestPersonnel(String testPersonnel) {
		this.testPersonnel = testPersonnel;
	}

	public String getTestResult() {
		return this.testResult;
	}

	public void setTestResult(String testResult) {
		this.testResult = testResult;
	}

	public String getTestTime() {
		return this.testTime;
	}

	public void setTestTime(String testTime) {
		this.testTime = testTime;
	}

}
