package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CircuitBoard generated by hbm2java
 */
public class CircuitBoard implements java.io.Serializable {

	private String backCoverSn;
	private TestBenchResults testBenchResults;
	private Boolean assembleFlag;
	private Boolean assembleStatus;
	private Set boardTests = new HashSet(0);
	private Set meters = new HashSet(0);
	private Set logs = new HashSet(0);
	private Set remarks = new HashSet(0);

	public CircuitBoard() {
	}

	public CircuitBoard(String backCoverSn) {
		this.backCoverSn = backCoverSn;
	}

	public CircuitBoard(String backCoverSn, TestBenchResults testBenchResults, Boolean assembleFlag,
			Boolean assembleStatus, Set boardTests, Set meters, Set logs, Set remarks) {
		this.backCoverSn = backCoverSn;
		this.testBenchResults = testBenchResults;
		this.assembleFlag = assembleFlag;
		this.assembleStatus = assembleStatus;
		this.boardTests = boardTests;
		this.meters = meters;
		this.logs = logs;
		this.remarks = remarks;
	}

	public String getBackCoverSn() {
		return this.backCoverSn;
	}

	public void setBackCoverSn(String backCoverSn) {
		this.backCoverSn = backCoverSn;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public Boolean getAssembleFlag() {
		return this.assembleFlag;
	}

	public void setAssembleFlag(Boolean assembleFlag) {
		this.assembleFlag = assembleFlag;
	}

	public Boolean getAssembleStatus() {
		return this.assembleStatus;
	}

	public void setAssembleStatus(Boolean assembleStatus) {
		this.assembleStatus = assembleStatus;
	}

	public Set getBoardTests() {
		return this.boardTests;
	}

	public void setBoardTests(Set boardTests) {
		this.boardTests = boardTests;
	}

	public Set getMeters() {
		return this.meters;
	}

	public void setMeters(Set meters) {
		this.meters = meters;
	}

	public Set getLogs() {
		return this.logs;
	}

	public void setLogs(Set logs) {
		this.logs = logs;
	}

	public Set getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Set remarks) {
		this.remarks = remarks;
	}

}
