package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * Configuration generated by hbm2java
 */
public class Configuration implements java.io.Serializable {

	private int configurationName;
	private Integer packageBoxSize;

	public Configuration() {
	}

	public Configuration(int configurationName) {
		this.configurationName = configurationName;
	}

	public Configuration(int configurationName, Integer packageBoxSize) {
		this.configurationName = configurationName;
		this.packageBoxSize = packageBoxSize;
	}

	public int getConfigurationName() {
		return this.configurationName;
	}

	public void setConfigurationName(int configurationName) {
		this.configurationName = configurationName;
	}

	public Integer getPackageBoxSize() {
		return this.packageBoxSize;
	}

	public void setPackageBoxSize(Integer packageBoxSize) {
		this.packageBoxSize = packageBoxSize;
	}

}
