package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Long id;
	private Boolean active;
	private String city;
	private String comment;
	private String country;
	private String customerGender;
	private String customerId;
	private String email;
	private String facebook;
	private String firstName;
	private String homeNumber;
	private String houseNumber;
	private String lastName;
	private String middleName;
	private String personalMobile;
	private String region;
	private String streetAddress;
	private String subCity;
	private String twitter;
	private Byte woreda;
	private String workMobile;
	private String workNumber;
	private String zipCode;

	public Customer() {
	}

	public Customer(Boolean active, String city, String comment, String country, String customerGender,
			String customerId, String email, String facebook, String firstName, String homeNumber, String houseNumber,
			String lastName, String middleName, String personalMobile, String region, String streetAddress,
			String subCity, String twitter, Byte woreda, String workMobile, String workNumber, String zipCode) {
		this.active = active;
		this.city = city;
		this.comment = comment;
		this.country = country;
		this.customerGender = customerGender;
		this.customerId = customerId;
		this.email = email;
		this.facebook = facebook;
		this.firstName = firstName;
		this.homeNumber = homeNumber;
		this.houseNumber = houseNumber;
		this.lastName = lastName;
		this.middleName = middleName;
		this.personalMobile = personalMobile;
		this.region = region;
		this.streetAddress = streetAddress;
		this.subCity = subCity;
		this.twitter = twitter;
		this.woreda = woreda;
		this.workMobile = workMobile;
		this.workNumber = workNumber;
		this.zipCode = zipCode;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCustomerGender() {
		return this.customerGender;
	}

	public void setCustomerGender(String customerGender) {
		this.customerGender = customerGender;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFacebook() {
		return this.facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getHomeNumber() {
		return this.homeNumber;
	}

	public void setHomeNumber(String homeNumber) {
		this.homeNumber = homeNumber;
	}

	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getPersonalMobile() {
		return this.personalMobile;
	}

	public void setPersonalMobile(String personalMobile) {
		this.personalMobile = personalMobile;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getSubCity() {
		return this.subCity;
	}

	public void setSubCity(String subCity) {
		this.subCity = subCity;
	}

	public String getTwitter() {
		return this.twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	public Byte getWoreda() {
		return this.woreda;
	}

	public void setWoreda(Byte woreda) {
		this.woreda = woreda;
	}

	public String getWorkMobile() {
		return this.workMobile;
	}

	public void setWorkMobile(String workMobile) {
		this.workMobile = workMobile;
	}

	public String getWorkNumber() {
		return this.workNumber;
	}

	public void setWorkNumber(String workNumber) {
		this.workNumber = workNumber;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

}
