package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

import java.sql.Timestamp;

/**
 * DeactivatedUser generated by hbm2java
 */
public class DeactivatedUser implements java.io.Serializable {

	private Long id;
	private Boolean adminUser;
	private String city;
	private String email;
	private String firstName;
	private String homeNumber;
	private String kebele;
	private String lastName;
	private String middleName;
	private String mobileNumber;
	private String nationality;
	private String phoneNumber;
	private String subcity;
	private String token;
	private Timestamp tokenExpireTime;
	private String userId;
	private String userPassword;
	private String woreda;
	private Long activeId;

	public DeactivatedUser() {
	}

	public DeactivatedUser(Boolean adminUser, String city, String email, String firstName, String homeNumber,
			String kebele, String lastName, String middleName, String mobileNumber, String nationality,
			String phoneNumber, String subcity, String token, Timestamp tokenExpireTime, String userId,
			String userPassword, String woreda, Long activeId) {
		this.adminUser = adminUser;
		this.city = city;
		this.email = email;
		this.firstName = firstName;
		this.homeNumber = homeNumber;
		this.kebele = kebele;
		this.lastName = lastName;
		this.middleName = middleName;
		this.mobileNumber = mobileNumber;
		this.nationality = nationality;
		this.phoneNumber = phoneNumber;
		this.subcity = subcity;
		this.token = token;
		this.tokenExpireTime = tokenExpireTime;
		this.userId = userId;
		this.userPassword = userPassword;
		this.woreda = woreda;
		this.activeId = activeId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(Boolean adminUser) {
		this.adminUser = adminUser;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getHomeNumber() {
		return this.homeNumber;
	}

	public void setHomeNumber(String homeNumber) {
		this.homeNumber = homeNumber;
	}

	public String getKebele() {
		return this.kebele;
	}

	public void setKebele(String kebele) {
		this.kebele = kebele;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getSubcity() {
		return this.subcity;
	}

	public void setSubcity(String subcity) {
		this.subcity = subcity;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Timestamp getTokenExpireTime() {
		return this.tokenExpireTime;
	}

	public void setTokenExpireTime(Timestamp tokenExpireTime) {
		this.tokenExpireTime = tokenExpireTime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getWoreda() {
		return this.woreda;
	}

	public void setWoreda(String woreda) {
		this.woreda = woreda;
	}

	public Long getActiveId() {
		return this.activeId;
	}

	public void setActiveId(Long activeId) {
		this.activeId = activeId;
	}

}
