package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * EffectivePermissions generated by hbm2java
 */
public class EffectivePermissions implements java.io.Serializable {

	private Long id;
	private String itemId;
	private String itemType;
	private String parentId;
	private String parentType;
	private Short rank;
	private String userId;

	public EffectivePermissions() {
	}

	public EffectivePermissions(String itemId, String itemType, String parentId, String parentType, Short rank,
			String userId) {
		this.itemId = itemId;
		this.itemType = itemType;
		this.parentId = parentId;
		this.parentType = parentType;
		this.rank = rank;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	public Short getRank() {
		return this.rank;
	}

	public void setRank(Short rank) {
		this.rank = rank;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
