package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private Long hjid;
	private Meter meter;
	private CircuitBoard circuitBoard;
	private Package package_;
	private String action;
	private String actionDetail;
	private String personnel;
	private String serialNumber;
	private Long time;

	public Log() {
	}

	public Log(Meter meter, CircuitBoard circuitBoard, Package package_, String action, String actionDetail,
			String personnel, String serialNumber, Long time) {
		this.meter = meter;
		this.circuitBoard = circuitBoard;
		this.package_ = package_;
		this.action = action;
		this.actionDetail = actionDetail;
		this.personnel = personnel;
		this.serialNumber = serialNumber;
		this.time = time;
	}

	public Long getHjid() {
		return this.hjid;
	}

	public void setHjid(Long hjid) {
		this.hjid = hjid;
	}

	public Meter getMeter() {
		return this.meter;
	}

	public void setMeter(Meter meter) {
		this.meter = meter;
	}

	public CircuitBoard getCircuitBoard() {
		return this.circuitBoard;
	}

	public void setCircuitBoard(CircuitBoard circuitBoard) {
		this.circuitBoard = circuitBoard;
	}

	public Package getPackage() {
		return this.package_;
	}

	public void setPackage(Package package_) {
		this.package_ = package_;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getActionDetail() {
		return this.actionDetail;
	}

	public void setActionDetail(String actionDetail) {
		this.actionDetail = actionDetail;
	}

	public String getPersonnel() {
		return this.personnel;
	}

	public void setPersonnel(String personnel) {
		this.personnel = personnel;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

}
