package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Meter generated by hbm2java
 */
public class Meter implements java.io.Serializable {

	private String frontCoverSn;
	private CircuitBoard circuitBoard;
	private Package package_;
	private String boxNumber;
	private String macAddress;
	private String modelNumber;
	private Boolean packFlag;
	private Boolean packStatus;
	private String propertyNumber;
	private Set logs = new HashSet(0);
	private Set remarks = new HashSet(0);
	private Set meterTests = new HashSet(0);

	public Meter() {
	}

	public Meter(String frontCoverSn) {
		this.frontCoverSn = frontCoverSn;
	}

	public Meter(String frontCoverSn, CircuitBoard circuitBoard, Package package_, String boxNumber, String macAddress,
			String modelNumber, Boolean packFlag, Boolean packStatus, String propertyNumber, Set logs, Set remarks,
			Set meterTests) {
		this.frontCoverSn = frontCoverSn;
		this.circuitBoard = circuitBoard;
		this.package_ = package_;
		this.boxNumber = boxNumber;
		this.macAddress = macAddress;
		this.modelNumber = modelNumber;
		this.packFlag = packFlag;
		this.packStatus = packStatus;
		this.propertyNumber = propertyNumber;
		this.logs = logs;
		this.remarks = remarks;
		this.meterTests = meterTests;
	}

	public String getFrontCoverSn() {
		return this.frontCoverSn;
	}

	public void setFrontCoverSn(String frontCoverSn) {
		this.frontCoverSn = frontCoverSn;
	}

	public CircuitBoard getCircuitBoard() {
		return this.circuitBoard;
	}

	public void setCircuitBoard(CircuitBoard circuitBoard) {
		this.circuitBoard = circuitBoard;
	}

	public Package getPackage() {
		return this.package_;
	}

	public void setPackage(Package package_) {
		this.package_ = package_;
	}

	public String getBoxNumber() {
		return this.boxNumber;
	}

	public void setBoxNumber(String boxNumber) {
		this.boxNumber = boxNumber;
	}

	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public String getModelNumber() {
		return this.modelNumber;
	}

	public void setModelNumber(String modelNumber) {
		this.modelNumber = modelNumber;
	}

	public Boolean getPackFlag() {
		return this.packFlag;
	}

	public void setPackFlag(Boolean packFlag) {
		this.packFlag = packFlag;
	}

	public Boolean getPackStatus() {
		return this.packStatus;
	}

	public void setPackStatus(Boolean packStatus) {
		this.packStatus = packStatus;
	}

	public String getPropertyNumber() {
		return this.propertyNumber;
	}

	public void setPropertyNumber(String propertyNumber) {
		this.propertyNumber = propertyNumber;
	}

	public Set getLogs() {
		return this.logs;
	}

	public void setLogs(Set logs) {
		this.logs = logs;
	}

	public Set getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Set remarks) {
		this.remarks = remarks;
	}

	public Set getMeterTests() {
		return this.meterTests;
	}

	public void setMeterTests(Set meterTests) {
		this.meterTests = meterTests;
	}

}
