package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * MeterAdj generated by hbm2java
 */
public class MeterAdj implements java.io.Serializable {

	private long hjid;
	private MeterTest meterTest;
	private String nominalVoltage;
	private String type;
	private String maxCurrent;
	private String sessionId;
	private String report;
	private String constant1;
	private String maxStartTime;
	private String maxCreepingTime;
	private String basicCurrent;
	private String first;
	private String minErrorTime;

	public MeterAdj() {
	}

	public MeterAdj(MeterTest meterTest) {
		this.meterTest = meterTest;
	}

	public MeterAdj(MeterTest meterTest, String nominalVoltage, String type, String maxCurrent, String sessionId, String report, String constant1, String maxStartTime, String maxCreepingTime, String basicCurrent, String first, String minErrorTime) {
       this.meterTest = meterTest;
       this.nominalVoltage = nominalVoltage;
       this.type = type;
       this.maxCurrent = maxCurrent;
       this.sessionId = sessionId;
       this.report = report;
       this.constant1 = constant1;
       this.maxStartTime = maxStartTime;
       this.maxCreepingTime = maxCreepingTime;
       this.basicCurrent = basicCurrent;
       this.first = first;
       this.minErrorTime = minErrorTime;
    }

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public MeterTest getMeterTest() {
		return this.meterTest;
	}

	public void setMeterTest(MeterTest meterTest) {
		this.meterTest = meterTest;
	}

	public String getNominalVoltage() {
		return this.nominalVoltage;
	}

	public void setNominalVoltage(String nominalVoltage) {
		this.nominalVoltage = nominalVoltage;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMaxCurrent() {
		return this.maxCurrent;
	}

	public void setMaxCurrent(String maxCurrent) {
		this.maxCurrent = maxCurrent;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	public String getConstant1() {
		return this.constant1;
	}

	public void setConstant1(String constant1) {
		this.constant1 = constant1;
	}

	public String getMaxStartTime() {
		return this.maxStartTime;
	}

	public void setMaxStartTime(String maxStartTime) {
		this.maxStartTime = maxStartTime;
	}

	public String getMaxCreepingTime() {
		return this.maxCreepingTime;
	}

	public void setMaxCreepingTime(String maxCreepingTime) {
		this.maxCreepingTime = maxCreepingTime;
	}

	public String getBasicCurrent() {
		return this.basicCurrent;
	}

	public void setBasicCurrent(String basicCurrent) {
		this.basicCurrent = basicCurrent;
	}

	public String get1st() {
        return this.first;
    }

	public void set1st(String first) {
        this.first = first;
    }

	public String getMinErrorTime() {
		return this.minErrorTime;
	}

	public void setMinErrorTime(String minErrorTime) {
		this.minErrorTime = minErrorTime;
	}

}
