package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * NoLoadTest generated by hbm2java
 */
public class NoLoadTest implements java.io.Serializable {

	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private Integer edgesCountNoLoad;
	private String alirTyp;
	private String evaluation;

	public NoLoadTest() {
	}

	public NoLoadTest(TestBase testBase) {
		this.testBase = testBase;
	}

	public NoLoadTest(TestBenchResults testBenchResults, TestBase testBase, Integer edgesCountNoLoad, String alirTyp,
			String evaluation) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.edgesCountNoLoad = edgesCountNoLoad;
		this.alirTyp = alirTyp;
		this.evaluation = evaluation;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public Integer getEdgesCountNoLoad() {
		return this.edgesCountNoLoad;
	}

	public void setEdgesCountNoLoad(Integer edgesCountNoLoad) {
		this.edgesCountNoLoad = edgesCountNoLoad;
	}

	public String getAlirTyp() {
		return this.alirTyp;
	}

	public void setAlirTyp(String alirTyp) {
		this.alirTyp = alirTyp;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

}
