package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * OperatingCurrentTest generated by hbm2java
 */
public class OperatingCurrentTest implements java.io.Serializable {

	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private Float metertConstant;
	private Float percentageError;
	private Float URange;
	private Float IRange;
	private Float errorPf05lag05a220v50hz0;
	private Float errorPf05lag10a220v50hz0;
	private Float errorPf05lag1a220v50hz0;
	private Float errorPf05lag20a220v50hz0;
	private Float errorPf05lag30a220v50hz0;
	private Float errorPf05lag5a220v50hz0;
	private Float errorPf05lag60a220v50hz0;
	private Float errorPf08lead05a220v50h0;
	private Float errorPf08lead10a220v50h0;
	private Float errorPf08lead1a220v50hz0;
	private Float errorPf08lead20a220v50h0;
	private Float errorPf08lead30a220v50h0;
	private Float errorPf08lead5a220v50hz0;
	private Float errorPf08lead60a220v50h0;
	private Float errorPf1025a220v50hz063;
	private Float errorPf105a220v50hz023;
	private Float errorPf110a220v50hz022;
	private Float errorPf11a220v50hz008;
	private Float errorPf120a220v50hz029;
	private Float errorPf130a220v50hz010;
	private Float errorPf15a220v50hz004;
	private Float errorPf160a220v50hz007;
	private Float maxError005ibTo01ibPf1;
	private Float maxError01ibTo02ibPf050;
	private Float maxError01ibTo02ibPf080;
	private Float maxError01ibToImaxPf1;
	private Float maxError02ibToImaxPf050;
	private Float maxError02ibToImaxPf080;
	private String evaluation;
	private Float metertConstantPf05;
	private Float percentageErrorPf05;
	private Float URangePf05;
	private Float IRangePf05;
	private String evaluationPf05;
	private Float metertConstantPf1;
	private Float percentageErrorPf1;
	private Float URangePf1;
	private Float IRangePf1;
	private String evaluationPf1;
	


	public OperatingCurrentTest(Float metertConstant, Float percentageError, Float URange, Float IRange, TestBenchResults testBenchResults, TestBase testBase, Float errorPf05lag05a220v50hz0,
			Float errorPf05lag10a220v50hz0, Float errorPf05lag1a220v50hz0, Float errorPf05lag20a220v50hz0,
			Float errorPf05lag30a220v50hz0, Float errorPf05lag5a220v50hz0, Float errorPf05lag60a220v50hz0,
			Float errorPf08lead05a220v50h0, Float errorPf08lead10a220v50h0, Float errorPf08lead1a220v50hz0,
			Float errorPf08lead20a220v50h0, Float errorPf08lead30a220v50h0, Float errorPf08lead5a220v50hz0,
			Float errorPf08lead60a220v50h0, Float errorPf1025a220v50hz063, Float errorPf105a220v50hz023,
			Float errorPf110a220v50hz022, Float errorPf11a220v50hz008, Float errorPf120a220v50hz029,
			Float errorPf130a220v50hz010, Float errorPf15a220v50hz004, Float errorPf160a220v50hz007,
			Float maxError005ibTo01ibPf1, Float maxError01ibTo02ibPf050, Float maxError01ibTo02ibPf080,
			Float maxError01ibToImaxPf1, Float maxError02ibToImaxPf050, Float maxError02ibToImaxPf080,
			String evaluation, Float IRangePf1, String evaluationPf1,
			Float metertConstantPf05, Float percentageErrorPf05, Float URangePf05, Float IRangePf05,
			String evaluationPf05, Float metertConstantPf1, Float percentageErrorPf1, Float URangePf1) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.errorPf05lag05a220v50hz0 = errorPf05lag05a220v50hz0;
		this.errorPf05lag10a220v50hz0 = errorPf05lag10a220v50hz0;
		this.errorPf05lag1a220v50hz0 = errorPf05lag1a220v50hz0;
		this.errorPf05lag20a220v50hz0 = errorPf05lag20a220v50hz0;
		this.errorPf05lag30a220v50hz0 = errorPf05lag30a220v50hz0;
		this.errorPf05lag5a220v50hz0 = errorPf05lag5a220v50hz0;
		this.errorPf05lag60a220v50hz0 = errorPf05lag60a220v50hz0;
		this.errorPf08lead05a220v50h0 = errorPf08lead05a220v50h0;
		this.errorPf08lead10a220v50h0 = errorPf08lead10a220v50h0;
		this.errorPf08lead1a220v50hz0 = errorPf08lead1a220v50hz0;
		this.errorPf08lead20a220v50h0 = errorPf08lead20a220v50h0;
		this.errorPf08lead30a220v50h0 = errorPf08lead30a220v50h0;
		this.errorPf08lead5a220v50hz0 = errorPf08lead5a220v50hz0;
		this.errorPf08lead60a220v50h0 = errorPf08lead60a220v50h0;
		this.errorPf1025a220v50hz063 = errorPf1025a220v50hz063;
		this.errorPf105a220v50hz023 = errorPf105a220v50hz023;
		this.errorPf110a220v50hz022 = errorPf110a220v50hz022;
		this.errorPf11a220v50hz008 = errorPf11a220v50hz008;
		this.errorPf120a220v50hz029 = errorPf120a220v50hz029;
		this.errorPf130a220v50hz010 = errorPf130a220v50hz010;
		this.errorPf15a220v50hz004 = errorPf15a220v50hz004;
		this.errorPf160a220v50hz007 = errorPf160a220v50hz007;
		this.maxError005ibTo01ibPf1 = maxError005ibTo01ibPf1;
		this.maxError01ibTo02ibPf050 = maxError01ibTo02ibPf050;
		this.maxError01ibTo02ibPf080 = maxError01ibTo02ibPf080;
		this.maxError01ibToImaxPf1 = maxError01ibToImaxPf1;
		this.maxError02ibToImaxPf050 = maxError02ibToImaxPf050;
		this.metertConstant = metertConstant;
		this.percentageError = percentageError;
		this.URange = URange;
		this.IRange = IRange;
		this.maxError02ibToImaxPf080 = maxError02ibToImaxPf080;
		this.evaluation = evaluation;
		this.metertConstantPf05 = metertConstantPf05;
		this.percentageErrorPf05 = percentageErrorPf05;
		this.URangePf05 = URangePf05;
		this.IRangePf05 = IRangePf05;
		this.evaluationPf05 = evaluationPf05;
		this.metertConstantPf1 = metertConstantPf1;
		this.percentageErrorPf1 = percentageErrorPf1;
		this.URangePf1 = URangePf1;
		this.IRangePf1 = IRangePf1;
		this.evaluationPf1 = evaluationPf1;
	}	
	public Float getMetertConstantPf05() {
		return metertConstantPf05;
	}
	public void setMetertConstantPf05(Float metertConstantPf05) {
		this.metertConstantPf05 = metertConstantPf05;
	}
	public Float getPercentageErrorPf05() {
		return percentageErrorPf05;
	}
	public void setPercentageErrorPf05(Float percentageErrorPf05) {
		this.percentageErrorPf05 = percentageErrorPf05;
	}
	public Float getURangePf05() {
		return URangePf05;
	}
	public void setURangePf05(Float uRangePf05) {
		URangePf05 = uRangePf05;
	}
	public Float getIRangePf05() {
		return IRangePf05;
	}
	public void setIRangePf05(Float iRangePf05) {
		IRangePf05 = iRangePf05;
	}
	public String getEvaluationPf05() {
		return evaluationPf05;
	}
	public void setEvaluationPf05(String evaluationPf05) {
		this.evaluationPf05 = evaluationPf05;
	}
	public Float getMetertConstantPf1() {
		return metertConstantPf1;
	}
	public void setMetertConstantPf1(Float metertConstantPf1) {
		this.metertConstantPf1 = metertConstantPf1;
	}
	public Float getPercentageErrorPf1() {
		return percentageErrorPf1;
	}
	public void setPercentageErrorPf1(Float percentageErrorPf1) {
		this.percentageErrorPf1 = percentageErrorPf1;
	}
	public Float getURangePf1() {
		return URangePf1;
	}
	public void setURangePf1(Float uRangePf1) {
		URangePf1 = uRangePf1;
	}
	public Float getIRangePf1() {
		return IRangePf1;
	}
	public void setIRangePf1(Float iRangePf1) {
		IRangePf1 = iRangePf1;
	}
	public String getEvaluationPf1() {
		return evaluationPf1;
	}
	public void setEvaluationPf1(String evaluationPf1) {
		this.evaluationPf1 = evaluationPf1;
	}
	public OperatingCurrentTest() {
	}

	public OperatingCurrentTest(TestBase testBase) {
		this.testBase = testBase;
	}
	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public Float getErrorPf05lag05a220v50hz0() {
		return this.errorPf05lag05a220v50hz0;
	}

	public void setErrorPf05lag05a220v50hz0(Float errorPf05lag05a220v50hz0) {
		this.errorPf05lag05a220v50hz0 = errorPf05lag05a220v50hz0;
	}

	public Float getErrorPf05lag10a220v50hz0() {
		return this.errorPf05lag10a220v50hz0;
	}

	public void setErrorPf05lag10a220v50hz0(Float errorPf05lag10a220v50hz0) {
		this.errorPf05lag10a220v50hz0 = errorPf05lag10a220v50hz0;
	}

	public Float getErrorPf05lag1a220v50hz0() {
		return this.errorPf05lag1a220v50hz0;
	}

	public void setErrorPf05lag1a220v50hz0(Float errorPf05lag1a220v50hz0) {
		this.errorPf05lag1a220v50hz0 = errorPf05lag1a220v50hz0;
	}

	public Float getErrorPf05lag20a220v50hz0() {
		return this.errorPf05lag20a220v50hz0;
	}

	public void setErrorPf05lag20a220v50hz0(Float errorPf05lag20a220v50hz0) {
		this.errorPf05lag20a220v50hz0 = errorPf05lag20a220v50hz0;
	}

	public Float getErrorPf05lag30a220v50hz0() {
		return this.errorPf05lag30a220v50hz0;
	}

	public void setErrorPf05lag30a220v50hz0(Float errorPf05lag30a220v50hz0) {
		this.errorPf05lag30a220v50hz0 = errorPf05lag30a220v50hz0;
	}

	public Float getErrorPf05lag5a220v50hz0() {
		return this.errorPf05lag5a220v50hz0;
	}

	public void setErrorPf05lag5a220v50hz0(Float errorPf05lag5a220v50hz0) {
		this.errorPf05lag5a220v50hz0 = errorPf05lag5a220v50hz0;
	}

	public Float getErrorPf05lag60a220v50hz0() {
		return this.errorPf05lag60a220v50hz0;
	}

	public void setErrorPf05lag60a220v50hz0(Float errorPf05lag60a220v50hz0) {
		this.errorPf05lag60a220v50hz0 = errorPf05lag60a220v50hz0;
	}

	public Float getErrorPf08lead05a220v50h0() {
		return this.errorPf08lead05a220v50h0;
	}

	public void setErrorPf08lead05a220v50h0(Float errorPf08lead05a220v50h0) {
		this.errorPf08lead05a220v50h0 = errorPf08lead05a220v50h0;
	}

	public Float getErrorPf08lead10a220v50h0() {
		return this.errorPf08lead10a220v50h0;
	}

	public void setErrorPf08lead10a220v50h0(Float errorPf08lead10a220v50h0) {
		this.errorPf08lead10a220v50h0 = errorPf08lead10a220v50h0;
	}

	public Float getErrorPf08lead1a220v50hz0() {
		return this.errorPf08lead1a220v50hz0;
	}

	public void setErrorPf08lead1a220v50hz0(Float errorPf08lead1a220v50hz0) {
		this.errorPf08lead1a220v50hz0 = errorPf08lead1a220v50hz0;
	}

	public Float getErrorPf08lead20a220v50h0() {
		return this.errorPf08lead20a220v50h0;
	}

	public void setErrorPf08lead20a220v50h0(Float errorPf08lead20a220v50h0) {
		this.errorPf08lead20a220v50h0 = errorPf08lead20a220v50h0;
	}

	public Float getErrorPf08lead30a220v50h0() {
		return this.errorPf08lead30a220v50h0;
	}

	public void setErrorPf08lead30a220v50h0(Float errorPf08lead30a220v50h0) {
		this.errorPf08lead30a220v50h0 = errorPf08lead30a220v50h0;
	}

	public Float getErrorPf08lead5a220v50hz0() {
		return this.errorPf08lead5a220v50hz0;
	}

	public void setErrorPf08lead5a220v50hz0(Float errorPf08lead5a220v50hz0) {
		this.errorPf08lead5a220v50hz0 = errorPf08lead5a220v50hz0;
	}

	public Float getErrorPf08lead60a220v50h0() {
		return this.errorPf08lead60a220v50h0;
	}

	public void setErrorPf08lead60a220v50h0(Float errorPf08lead60a220v50h0) {
		this.errorPf08lead60a220v50h0 = errorPf08lead60a220v50h0;
	}

	public Float getErrorPf1025a220v50hz063() {
		return this.errorPf1025a220v50hz063;
	}

	public void setErrorPf1025a220v50hz063(Float errorPf1025a220v50hz063) {
		this.errorPf1025a220v50hz063 = errorPf1025a220v50hz063;
	}

	public Float getErrorPf105a220v50hz023() {
		return this.errorPf105a220v50hz023;
	}

	public void setErrorPf105a220v50hz023(Float errorPf105a220v50hz023) {
		this.errorPf105a220v50hz023 = errorPf105a220v50hz023;
	}

	public Float getErrorPf110a220v50hz022() {
		return this.errorPf110a220v50hz022;
	}

	public void setErrorPf110a220v50hz022(Float errorPf110a220v50hz022) {
		this.errorPf110a220v50hz022 = errorPf110a220v50hz022;
	}

	public Float getErrorPf11a220v50hz008() {
		return this.errorPf11a220v50hz008;
	}

	public void setErrorPf11a220v50hz008(Float errorPf11a220v50hz008) {
		this.errorPf11a220v50hz008 = errorPf11a220v50hz008;
	}

	public Float getErrorPf120a220v50hz029() {
		return this.errorPf120a220v50hz029;
	}

	public void setErrorPf120a220v50hz029(Float errorPf120a220v50hz029) {
		this.errorPf120a220v50hz029 = errorPf120a220v50hz029;
	}

	public Float getErrorPf130a220v50hz010() {
		return this.errorPf130a220v50hz010;
	}

	public void setErrorPf130a220v50hz010(Float errorPf130a220v50hz010) {
		this.errorPf130a220v50hz010 = errorPf130a220v50hz010;
	}

	public Float getErrorPf15a220v50hz004() {
		return this.errorPf15a220v50hz004;
	}

	public void setErrorPf15a220v50hz004(Float errorPf15a220v50hz004) {
		this.errorPf15a220v50hz004 = errorPf15a220v50hz004;
	}

	public Float getErrorPf160a220v50hz007() {
		return this.errorPf160a220v50hz007;
	}

	public void setErrorPf160a220v50hz007(Float errorPf160a220v50hz007) {
		this.errorPf160a220v50hz007 = errorPf160a220v50hz007;
	}

	public Float getMaxError005ibTo01ibPf1() {
		return this.maxError005ibTo01ibPf1;
	}

	public void setMaxError005ibTo01ibPf1(Float maxError005ibTo01ibPf1) {
		this.maxError005ibTo01ibPf1 = maxError005ibTo01ibPf1;
	}

	public Float getMaxError01ibTo02ibPf050() {
		return this.maxError01ibTo02ibPf050;
	}

	public void setMaxError01ibTo02ibPf050(Float maxError01ibTo02ibPf050) {
		this.maxError01ibTo02ibPf050 = maxError01ibTo02ibPf050;
	}

	public Float getMaxError01ibTo02ibPf080() {
		return this.maxError01ibTo02ibPf080;
	}

	public void setMaxError01ibTo02ibPf080(Float maxError01ibTo02ibPf080) {
		this.maxError01ibTo02ibPf080 = maxError01ibTo02ibPf080;
	}

	public Float getMaxError01ibToImaxPf1() {
		return this.maxError01ibToImaxPf1;
	}

	public void setMaxError01ibToImaxPf1(Float maxError01ibToImaxPf1) {
		this.maxError01ibToImaxPf1 = maxError01ibToImaxPf1;
	}

	public Float getMaxError02ibToImaxPf050() {
		return this.maxError02ibToImaxPf050;
	}
	
	public Float getMetertConstant() {
		return this.metertConstant;
	}
	
	public void setMetertConstant(Float metertConstant) {
		this.metertConstant = metertConstant;
	}
	
	public void setMaxError02ibToImaxPf050(Float maxError02ibToImaxPf050) {
		this.maxError02ibToImaxPf050 = maxError02ibToImaxPf050;
	}

	public Float getMaxError02ibToImaxPf080() {
		return this.maxError02ibToImaxPf080;
	}

	public void setMaxError02ibToImaxPf080(Float maxError02ibToImaxPf080) {
		this.maxError02ibToImaxPf080 = maxError02ibToImaxPf080;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}
	
	public Float getPercentageError() {
		return this.percentageError;
	}

	public void setPercentageError(Float percentageError) {
		this.percentageError = percentageError;
	}

	public Float getURange() {
		return this.URange;
	}

	public void setURange(Float URange) {
		this.URange = URange;
	}

	public Float getIRange() {
		return this.IRange;
	}

	public void setIRange(Float IRange) {
		this.IRange = IRange;
	}

}
