package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Package generated by hbm2java
 */
public class Package implements java.io.Serializable {

	private String packageSn;
	private Boolean shipmentFlag;
	private Boolean shipmentStatus;
	private Set remarks = new HashSet(0);
	private Set meters = new HashSet(0);
	private Set logs = new HashSet(0);

	public Package() {
	}

	public Package(String packageSn) {
		this.packageSn = packageSn;
	}

	public Package(String packageSn, Boolean shipmentFlag, Boolean shipmentStatus, Set remarks, Set meters, Set logs) {
		this.packageSn = packageSn;
		this.shipmentFlag = shipmentFlag;
		this.shipmentStatus = shipmentStatus;
		this.remarks = remarks;
		this.meters = meters;
		this.logs = logs;
	}

	public String getPackageSn() {
		return this.packageSn;
	}

	public void setPackageSn(String packageSn) {
		this.packageSn = packageSn;
	}

	public Boolean getShipmentFlag() {
		return this.shipmentFlag;
	}

	public void setShipmentFlag(Boolean shipmentFlag) {
		this.shipmentFlag = shipmentFlag;
	}

	public Boolean getShipmentStatus() {
		return this.shipmentStatus;
	}

	public void setShipmentStatus(Boolean shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	public Set getRemarks() {
		return this.remarks;
	}

	public void setRemarks(Set remarks) {
		this.remarks = remarks;
	}

	public Set getMeters() {
		return this.meters;
	}

	public void setMeters(Set meters) {
		this.meters = meters;
	}

	public Set getLogs() {
		return this.logs;
	}

	public void setLogs(Set logs) {
		this.logs = logs;
	}

}
