package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * Remark generated by hbm2java
 */
public class Remark implements java.io.Serializable {

	private Long hjid;
	private Meter meter;
	private CircuitBoard circuitBoard;
	private Package package_;
	private Boolean activeStatus;
	private String content;
	private Long time;
	private String userId;

	public Remark() {
	}

	public Remark(Meter meter, CircuitBoard circuitBoard, Package package_, Boolean activeStatus, String content,
			Long time, String userId) {
		this.meter = meter;
		this.circuitBoard = circuitBoard;
		this.package_ = package_;
		this.activeStatus = activeStatus;
		this.content = content;
		this.time = time;
		this.userId = userId;
	}

	public Long getHjid() {
		return this.hjid;
	}

	public void setHjid(Long hjid) {
		this.hjid = hjid;
	}

	public Meter getMeter() {
		return this.meter;
	}

	public void setMeter(Meter meter) {
		this.meter = meter;
	}

	public CircuitBoard getCircuitBoard() {
		return this.circuitBoard;
	}

	public void setCircuitBoard(CircuitBoard circuitBoard) {
		this.circuitBoard = circuitBoard;
	}

	public Package getPackage() {
		return this.package_;
	}

	public void setPackage(Package package_) {
		this.package_ = package_;
	}

	public Boolean getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(Boolean activeStatus) {
		this.activeStatus = activeStatus;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
