package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * ScAdjustment generated by hbm2java
 */
public class ScAdjustment implements java.io.Serializable {

	private long hjid;
	private TestBase testBase;
	private Float metertConstant;
	private Float percentageError;
	private String evaluation;
	private Float URange;
	private Float IRange;

	public ScAdjustment() {
	}

	public ScAdjustment(TestBase testBase) {
		this.testBase = testBase;
	}

	public ScAdjustment(TestBase testBase, Float metertConstant, Float percentageError, Float URange, Float IRange, String evaluation) {
		this.testBase = testBase;
		this.metertConstant = metertConstant;
		this.percentageError = percentageError;
		this.evaluation = evaluation;
		this.URange = URange;
		this.IRange = IRange;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public String getEvaluation() {
		return evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}
	
	public Float getMetertConstant() {
		return this.metertConstant;
	}

	public void setMetertConstant(Float metertConstant) {
		this.metertConstant = metertConstant;
	}

	public Float getPercentageError() {
		return this.percentageError;
	}

	public void setPercentageError(Float percentageError) {
		this.percentageError = percentageError;
	}

	public Float getURange() {
		return this.URange;
	}

	public void setURange(Float URange) {
		this.URange = URange;
	}

	public Float getIRange() {
		return this.IRange;
	}

	public void setIRange(Float IRange) {
		this.IRange = IRange;
	}

}
