package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * ShuntImpedanceTest generated by hbm2java
 */
public class ShuntImpedanceTest implements java.io.Serializable {

	private long hjid;
	private TestBenchResults testBenchResults;
	private TestBase testBase;
	private Float resistanceShunt;

	public ShuntImpedanceTest() {
	}

	public ShuntImpedanceTest(TestBase testBase) {
		this.testBase = testBase;
	}

	public ShuntImpedanceTest(TestBenchResults testBenchResults, TestBase testBase, Float resistanceShunt) {
		this.testBenchResults = testBenchResults;
		this.testBase = testBase;
		this.resistanceShunt = resistanceShunt;
	}

	public long getHjid() {
		return this.hjid;
	}

	public void setHjid(long hjid) {
		this.hjid = hjid;
	}

	public TestBenchResults getTestBenchResults() {
		return this.testBenchResults;
	}

	public void setTestBenchResults(TestBenchResults testBenchResults) {
		this.testBenchResults = testBenchResults;
	}

	public TestBase getTestBase() {
		return this.testBase;
	}

	public void setTestBase(TestBase testBase) {
		this.testBase = testBase;
	}

	public Float getResistanceShunt() {
		return this.resistanceShunt;
	}

	public void setResistanceShunt(Float resistanceShunt) {
		this.resistanceShunt = resistanceShunt;
	}

}
