package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * TestBase generated by hbm2java
 */
public class TestBase implements java.io.Serializable {

	private Long hjid;
	private Boolean active;
	private String comment;
	private String evaluation;
	private String meterPosition;
	private String frontCoverSn;
	private String sampleBased;
	private String sessionId;
	private String testBenchName;
	private String testEndTime;
	private String testPeronnel;
	private String testPlace;
	private String testStartTime;
	private String report;
	private ShuntImpedanceTest shuntImpedanceTest;
	private NeutralImpedanceTest neutralImpedanceTest;
	private EnergyRegisterTest energyRegisterTest;
	private ScAdjustment scAdjustment;
	private EnergyAndTamperClearTest energyAndTamperClearTest;
	private OperatingCurrentTest operatingCurrentTest;
	private StartingCurrentTest startingCurrentTest;
	private CalibrationTest calibrationTest;
	private NoLoadTest noLoadTest;

	public TestBase() {
	}

	public TestBase(Boolean active, String frontCoverSn, String comment, String evaluation, String meterPosition, String sampleBased,
			String sessionId, String testBenchName, String testEndTime, String testPeronnel, String testPlace,
			String testStartTime, String report, ShuntImpedanceTest shuntImpedanceTest,
			NeutralImpedanceTest neutralImpedanceTest, EnergyRegisterTest energyRegisterTest, ScAdjustment scAdjustment,
			EnergyAndTamperClearTest energyAndTamperClearTest, OperatingCurrentTest operatingCurrentTest,
			StartingCurrentTest startingCurrentTest, CalibrationTest calibrationTest, NoLoadTest noLoadTest) {
		this.active = active;
		this.comment = comment;
		this.evaluation = evaluation;
		this.frontCoverSn = frontCoverSn;
		this.meterPosition = meterPosition;
		this.sampleBased = sampleBased;
		this.sessionId = sessionId;
		this.testBenchName = testBenchName;
		this.testEndTime = testEndTime;
		this.testPeronnel = testPeronnel;
		this.testPlace = testPlace;
		this.testStartTime = testStartTime;
		this.report = report;
		this.shuntImpedanceTest = shuntImpedanceTest;
		this.neutralImpedanceTest = neutralImpedanceTest;
		this.energyRegisterTest = energyRegisterTest;
		this.scAdjustment = scAdjustment;
		this.energyAndTamperClearTest = energyAndTamperClearTest;
		this.operatingCurrentTest = operatingCurrentTest;
		this.startingCurrentTest = startingCurrentTest;
		this.calibrationTest = calibrationTest;
		this.noLoadTest = noLoadTest;
	}

	public Long getHjid() {
		return this.hjid;
	}

	public void setHjid(Long hjid) {
		this.hjid = hjid;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	public String getMeterPosition() {
		return this.meterPosition;
	}

	public void setMeterPosition(String meterPosition) {
		this.meterPosition = meterPosition;
	}
	
	public String getFrontCoverSn() {
		return this.frontCoverSn;
	}

	public void setFrontCoverSn(String frontCoverSn) {
		this.frontCoverSn = frontCoverSn;
	}

	public String getSampleBased() {
		return this.sampleBased;
	}

	public void setSampleBased(String sampleBased) {
		this.sampleBased = sampleBased;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getTestBenchName() {
		return this.testBenchName;
	}

	public void setTestBenchName(String testBenchName) {
		this.testBenchName = testBenchName;
	}

	public String getTestEndTime() {
		return this.testEndTime;
	}

	public void setTestEndTime(String testEndTime) {
		this.testEndTime = testEndTime;
	}

	public String getTestPeronnel() {
		return this.testPeronnel;
	}

	public void setTestPeronnel(String testPeronnel) {
		this.testPeronnel = testPeronnel;
	}

	public String getTestPlace() {
		return this.testPlace;
	}

	public void setTestPlace(String testPlace) {
		this.testPlace = testPlace;
	}

	public String getTestStartTime() {
		return this.testStartTime;
	}

	public void setTestStartTime(String testStartTime) {
		this.testStartTime = testStartTime;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	public ShuntImpedanceTest getShuntImpedanceTest() {
		return this.shuntImpedanceTest;
	}

	public void setShuntImpedanceTest(ShuntImpedanceTest shuntImpedanceTest) {
		this.shuntImpedanceTest = shuntImpedanceTest;
	}

	public NeutralImpedanceTest getNeutralImpedanceTest() {
		return this.neutralImpedanceTest;
	}

	public void setNeutralImpedanceTest(NeutralImpedanceTest neutralImpedanceTest) {
		this.neutralImpedanceTest = neutralImpedanceTest;
	}

	public EnergyRegisterTest getEnergyRegisterTest() {
		return this.energyRegisterTest;
	}

	public void setEnergyRegisterTest(EnergyRegisterTest energyRegisterTest) {
		this.energyRegisterTest = energyRegisterTest;
	}

	public ScAdjustment getScAdjustment() {
		return this.scAdjustment;
	}

	public void setScAdjustment(ScAdjustment scAdjustment) {
		this.scAdjustment = scAdjustment;
	}

	public EnergyAndTamperClearTest getEnergyAndTamperClearTest() {
		return this.energyAndTamperClearTest;
	}

	public void setEnergyAndTamperClearTest(EnergyAndTamperClearTest energyAndTamperClearTest) {
		this.energyAndTamperClearTest = energyAndTamperClearTest;
	}

	public OperatingCurrentTest getOperatingCurrentTest() {
		return this.operatingCurrentTest;
	}

	public void setOperatingCurrentTest(OperatingCurrentTest operatingCurrentTest) {
		this.operatingCurrentTest = operatingCurrentTest;
	}

	public StartingCurrentTest getStartingCurrentTest() {
		return this.startingCurrentTest;
	}

	public void setStartingCurrentTest(StartingCurrentTest startingCurrentTest) {
		this.startingCurrentTest = startingCurrentTest;
	}

	public CalibrationTest getCalibrationTest() {
		return this.calibrationTest;
	}

	public void setCalibrationTest(CalibrationTest calibrationTest) {
		this.calibrationTest = calibrationTest;
	}

	public NoLoadTest getNoLoadTest() {
		return this.noLoadTest;
	}

	public void setNoLoadTest(NoLoadTest noLoadTest) {
		this.noLoadTest = noLoadTest;
	}

}
