package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * UserGroupRolesMap generated by hbm2java
 */
public class UserGroupRolesMap implements java.io.Serializable {

	private UserGroupRolesMapId id;
	private Role role;
	private UserGroup userGroup;

	public UserGroupRolesMap() {
	}

	public UserGroupRolesMap(UserGroupRolesMapId id, Role role, UserGroup userGroup) {
		this.id = id;
		this.role = role;
		this.userGroup = userGroup;
	}

	public UserGroupRolesMapId getId() {
		return this.id;
	}

	public void setId(UserGroupRolesMapId id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

}
