package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * UserGroupUsersMap generated by hbm2java
 */
public class UserGroupUsersMap implements java.io.Serializable {

	private UserGroupUsersMapId id;
	private User user;
	private UserGroup userGroup;

	public UserGroupUsersMap() {
	}

	public UserGroupUsersMap(UserGroupUsersMapId id, User user, UserGroup userGroup) {
		this.id = id;
		this.user = user;
		this.userGroup = userGroup;
	}

	public UserGroupUsersMapId getId() {
		return this.id;
	}

	public void setId(UserGroupUsersMapId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

}
