package com.dventus;
// Generated Dec 8, 2022, 4:50:42 PM by Hibernate Tools 6.1.3.Final

/**
 * UserGroupRolesMapId generated by hbm2java
 */
public class UserGroupRolesMapId implements java.io.Serializable {

	private long GId;
	private long RId;

	public UserGroupRolesMapId() {
	}

	public UserGroupRolesMapId(long GId, long RId) {
		this.GId = GId;
		this.RId = RId;
	}

	public long getGId() {
		return this.GId;
	}

	public void setGId(long GId) {
		this.GId = GId;
	}

	public long getRId() {
		return this.RId;
	}

	public void setRId(long RId) {
		this.RId = RId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupRolesMapId))
			return false;
		UserGroupRolesMapId castOther = (UserGroupRolesMapId) other;

		return (this.getGId() == castOther.getGId()) && (this.getRId() == castOther.getRId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGId();
		result = 37 * result + (int) this.getRId();
		return result;
	}

}
